# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Untitled3.o Untitled4.o
LINKOBJ  = Untitled3.o Untitled4.o
LIBS     = -L"D:/Dev-C++/Dev-Cpp/MinGW64/lib" -L"D:/Dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Dev-C++/Dev-Cpp/MinGW64/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev-C++/Dev-Cpp/MinGW64/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-C++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project2.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Untitled3.o: Untitled3.c
	$(CC) -c Untitled3.c -o Untitled3.o $(CFLAGS)

Untitled4.o: Untitled4.c
	$(CC) -c Untitled4.c -o Untitled4.o $(CFLAGS)
